platform :ios, '8.0'

target 'RNDemo' do
  # use_frameworks!

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'RNDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
